app:
  title: Summer Framework
  version: 1.0.0

# standard structure for datasource, mail, etc:
summer:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: 159357
    driver-class-name: org.postgresql.Driver